import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display } from "next/font/google"
import PrivateRoute from "@/components/PrivateRoute";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-playfair',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // rember padding is applied globally 
    <html lang="en">
      <body
        className={`${playfair.variable} font-normal antialiased px-3 lg:px-14 text-sm py-2`}
         cz-shortcut-listen="true"
      >
        <PrivateRoute>
          {children}
        </PrivateRoute>
      </body>
    </html>
  );
}
