import type { Metadata } from "next";
import "./globals.css";
import { Playfair_Display } from "next/font/google"
import PrivateRoute from "@/components/PrivateRoute";
import { ThemeProvider } from "next-themes";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['500'],
  variable: '--font-playfair',
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // rember padding is applied globally 
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${playfair.variable} font-normal antialiased px-3 lg:px-14 text-sm py-2`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          <PrivateRoute>{children}</PrivateRoute>
        </ThemeProvider>
      </body>
    </html>
  );
}
